# GitLab CI Steps
image: "ghcr.io/cirruslabs/flutter:stable"

stages:
  - build
  - test
  - quality

android_build:
  stage: build
  tags:
    - amd64
  before_script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - echo "flutter.targetSdkVersion=34" > android/local.properties
    - echo "flutter.compileSdkVersion=34" >> android/local.properties
    - echo "keyAlias=upload" > android/key.properties
    - echo "keyPassword=$KEYSTORE_PASSWORD" >> android/key.properties
    - echo "storeFile=./.secure_files/upload-keystore.jks" >> android/key.properties
    - echo "storePassword=$KEYSTORE_PASSWORD" >> android/key.properties
  script:
    - flutter build apk --target=lib/expenses.dart --split-per-abi
  cache:
    key:
      files:
        - android/app/build.gradle
        - pubspec.lock
    paths:
      - build
      - android/.gradle
    policy: pull-push

test:
  stage: test
  before_script:
    - flutter pub global activate junitreport
    - export PATH="$PATH:$HOME/.pub-cache/bin"
  script:
    - flutter test --machine --coverage | tojunit -o report.xml
    - lcov --summary coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: coverage
    paths:
      - $CI_PROJECT_DIR/coverage
    reports:
      junit: report.xml

code_quality:
  stage: quality
  before_script:
    - flutter pub global activate dart_code_metrics
    - export PATH="$PATH:$HOME/.pub-cache/bin"
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
