name: Android Build

on:
  push:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.0
          cache: true
      - run: flutter config --no-analytics
      - run: flutter config --no-cli-animations
      - run: flutter pub get
      - run: flutter build apk --target=lib/expenses.dart --split-per-abi
      - run: mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk Expenses-arm64-v8a.apk
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Expenses-arm64-v8a.apk"
          tag: ${{ github.ref_name }}
          prerelease: true
          allowUpdates: true