name: Android Build

on:
  push:
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.4
          cache: true
      - name: Flutter configs
        run: |
          flutter config --no-cli-animations
          flutter config --no-analytics
      - name: Get packages
        run: flutter pub get
      - name: Setup Key Store for application signing
        shell: bash
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > app/keystore.jks
          echo "keyAlias=upload" > key.properties
          echo "keyPassword=${{ secrets.KEYSTORE_PASSWORD }}" >> key.properties
          echo "storeFile=keystore.jks" >> key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> key.properties
          echo "flutter.targetSdkVersion=35" > local.properties
          echo "flutter.compileSdkVersion=35" >> local.properties
          echo "flutter.ndkVersion=27.0.12077973" >> local.properties
        working-directory: ./android
      - name: Flutter build APK
        run: flutter build apk --split-per-abi
      - name: Rename artifacts
        run: mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk Expenses-arm64-v8a-signed-${{ github.ref_name }}.apk
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Expenses-arm64-v8a-signed-${{ github.ref_name }}.apk"
          tag: ${{ github.ref_name }}
          prerelease: true
          allowUpdates: true
