name: Android Build

on:
  push:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.3
          cache: true
      - run: flutter config --no-cli-animations
      - run: flutter config --no-analytics
      - run: flutter pub get
      - name: Setup Key Store for application signing
        shell: bash
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > app/keystore.jks
          echo "keyAlias=upload" > key.properties
          echo "keyPassword=${{ secrets.KEYSTORE_PASSWORD }}" >> key.properties
          echo "storeFile=keystore.jks" >> key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> key.properties
          ls app/
        working-directory: ./android
      - run: flutter build apk --split-per-abi
      - run: mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk Expenses-arm64-v8a-signed-${{ github.ref_name }}.apk
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Expenses-arm64-v8a-signed-${{ github.ref_name }}.apk"
          tag: ${{ github.ref_name }}
          prerelease: true
          allowUpdates: true