name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.0
          cache: true
      - run: flutter config --no-cli-animations
      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter test

  