name: Linux Build

on:
  push:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.0
          cache: true
      - run: flutter config --no-analytics
      - run: flutter config --no-cli-animations
      - run: flutter pub get
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux --target=lib/expenses.dart
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: expenses_app_linux
          path: build/linux/x64/release/bundle
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'tar'
          filename: Expenses-linux.tar.gz
          path: build/linux/x64/release/bundle
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Expenses-linux.tar.gz"
          tag: ${{ github.ref_name }}
          prerelease: true
          allowUpdates: true